apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  myapp-argo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 483034414867.dkr.ecr.us-east-1.amazonaws.com/itamar_ecr/latest
    argocd-image-updater.argoproj.io/itamar_ecr.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds            #Setting git credential
    argocd-image-updater.argoproj.io/git-branch: main                                          #git branch where your workflow exists
    argocd-image-updater.argoproj.io/itamar_ecr.force-update: "true"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/itamarg84/module3.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
